FROM node:22-slim

WORKDIR /app

RUN apt update && apt install -y python3 make gcc g++
COPY package.json  yarn.lock /app/
RUN yarn 

COPY . .
RUN yarn build

EXPOSE 5001

CMD ["yarn", "run", "prod"]

#CMD ["tail", "-f", "/dev/null"]
