FROM node:18-slim

WORKDIR /app

RUN apt update && apt install -y python3 make gcc g++
COPY package.json  yarn.lock /app/
RUN yarn 

COPY . .
RUN yarn build

# Good to copy all templates to relevant directory
RUN mkdir -p /tmp/templates

EXPOSE 5001

CMD ["npm", "run", "prod"]

#CMD ["tail", "-f", "/dev/null"]
